### ISSUE TITLE
#0007 likelihood calculation

### ISSUE THREAD

**Issue by adrianhauber** [PEtab-dev/petab_test_suite#25]
We (dMod & d2d teams) find a different likelihood value for test case 0007. Could someone please check if there is an error in the solutions file?

```
data = [0.2000   -0.0969]; %second datapoint log10-transformed
simus = [0.4286   -0.2430]; %second simulation log10-transformed
errors = [0.5000    0.6000];

DataContribution = -((data-simus).^2)./(2*errors.^2) %[-0.1045   -0.0297]
ErrorContribution = -1/2 * log(2*pi*errors.^2) %[-0.2258   -0.4081]

llh = sum(DataContribution + ErrorContribution) %-0.7681
```

**Comment by yannikschaelte** [comment]
Hi @adrianhauber,

we have recently discussed this in #11. There was indeed an error with 0007, so you may need to update the repository. The true likelihood should now be -1.378941036858004.

The thing is that the ErrorContribution above must also include terms from applying the transformation rule. This adds an offset, which however is important when comparing likelihoods  e.g. for model selection. It should read

```
ErrorContribution = -1/2 * log(2*pi*errors.^2*data.^2*log(10)^2)
```
Does that give you the correct result?

**Comment by yannikschaelte** [comment]
for case 0016, the log(10) term would be omitted, since there we assume log scaling, not log10 scaling.

**Comment by marcusrosenblatt** [comment]
Hi,

so as you show here [ https://github.com/PEtab-dev/PEtab/blob/develop/petab/calculate.py#L356], you assume a normal distribution for the measurement, while fitting (observable) is on log-scale.  Isn't this a little bit confusing? Normally you use the log-transformation in the observables to account for log-normally distributed measurements (like e.g. in western blot). 
I think this is where our confusion came from. I thought that writing "log10" as observableTransformation in the PEtab file implies that the data is assumed to be log-normally distributed. Ok, I get this point now.

But then: Where in PEtab is the possibility to specify log-normally distributed measurements? And should we not have a test case for this, too?

Best,
Marcus

**Comment by yannikschaelte** [comment]
Not sure what you mean. We do intend to use a log10-normal distribution here, i.e. a distribution such that log10(y) is normally distributed. Or what would you understand under log-normal?

**Comment by marcusrosenblatt** [comment]
We have the same definition of log-normal. I am still searching for an explanation why the retransformation has to take place for the likelihood calculation. For me, after the log-transformation, the log(observable) is the (new) random variable of interest. This new random variable is normally distributed. And then I would not have to retransform for the calculation of the likelihood. But maybe this is somehow a wrong assumption.

Anyway we decided to not support it in dMod because statistically it makes no difference. I just would like to understand it ;-)

**Comment by yannikschaelte** [comment]
What exactly do you mean by retransformation? You mean the additional  ``0.5*log(2*pi*sigma**2*m**2*log(10)**2)``, or of that only the `` 0.5*log(m**2*log(10)**2) + ``?

**Comment by yannikschaelte** [comment]
That is because transforming y -> log(y) and then having a normal distribution on those values, and assuming a log-normal distribution on y are statistically two different things:

In the second case we still say that we want to integrate over all y, not log(y), and therefore we need to apply a [measure transformation](https://de.wikipedia.org/wiki/Transformationssatz) so that the whole integral over the probability density integrates to 1. that is where the additional ``0.5*log(**2*log(10)**2)`` comes from.

By contrast, in the first case we assume that our probability space is on z=log(y), not y. When comparing different measurement models and doing model selection, this may become relevant (and more than just an additive constant).

**Comment by yannikschaelte** [comment]
hope that became clearer now ... if something is still unclear, happy to discuss, closing for the moment.
